item-shovel:
    material: 'IRON_SHOVEL'
    player-head-texture: "Значение с сайта https://minecraft-heads.com/ For Developers: Value"
    display-name: "§f§lЛопата CASPER"
    potion-effects:
      INCREASE_DAMAGE:
        duration: 60 #секунды
        amplifier: 3 #уровень эффекта
        ambient: true #default - true
        particles: true #default - true



    enchants:
      DIG_SPEED: 2
      DURABILITY: 1
      LOOT_BONUS_BLOCKS: 2

    tripped-arrow-effects:
      NIGHT_VISION:
        long-duration: true
        second-level: true

    attribute-modifiers:
      GENERIC_MAX_HEALTH: #org.bukkit.attribute.Attribute
        modifier: 1.0
        modify-type: ADD_NUMBER #org.bukkit.attribute.AttributeModifier.Operation
        equipments-slots: #org.bukkit.inventory.EquipmentSlot если не указать не одного слота то будет работать везде
          - OFF_HAND


