item-shovel:
  material: 'IRON_SHOVEL' #org.bukkit.Material
  player-head-texture: "Значение с сайта https://minecraft-heads.com/ For Developers: Value"
  rgb: 153, 217, 236
  display-name: "§f§lЛопаточка"
  lore:
    - '§fописание'
    - '§aпредмета'
  amount: 14 #default 1
  unbreakable: true #default false
  custom-model-data: 123
  localized-name: "localized-name"
  fake-enchant: true #default false

  enchants:
    DIG_SPEED: 2
    DURABILITY: 1
    LOOT_BONUS_BLOCKS: 2

  item-flags:
    HIDE_ENCHANTS: true  #org.bukkit.inventory.ItemFlag

  tripped-arrow-effects:
    NIGHT_VISION:
      long-duration: true
      second-level: true

  attribute-modifiers:
    GENERIC_MAX_HEALTH: #org.bukkit.attribute.Attribute
      modifier: 1.0
      modify-type: ADD_NUMBER #org.bukkit.attribute.AttributeModifier.Operation
      equipments-slots: #org.bukkit.inventory.EquipmentSlot если не указать не одного слота то будет работать везде
        - OFF_HAND

  potion-data:
    potion-type: WATER #org.bukkit.potion.PotionType
    extended: true #default - false
    upgraded: true #default - false

  potion-effects:
    INCREASE_DAMAGE: #org.bukkit.potion.PotionEffectType
      duration: 60 #секунды
      amplifier: 3 #уровень эффекта
      ambient: true #default - true
      particles: true #default - true









#Bukkit
any-section-0:
  boss-bar:
    color: 'RED'
    style: 'SOLID'
    flags:
      - 'PLAY_BOSS_MUSIC'


#Paper
any-section-1:
  boss-bar:
    color: 'RED'
    overlay: 'PROGRESS'
    flags:
      - 'DARKEN_SCREEN'



  schematic:
    structure:
      WHITE_STAINED_GLASS: 1
      AIR: 2
      LANTERN: 3

    blocks: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 3, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    size:
      x: 7
      z: 7

    offset:
      x: 4
      y: 4
      z: 1





menu:
  size: 54
  title: "Название"
  content:
    item-1:
      menu-slot: 53
      material: Stone
      close-button: true
      click-commands:
        - 'shop'

    back-ground-item-1:
      menu-slots:
        - '2-3'
        - '5-6'
        - '18-18'
        - '26-27'
        - '35-35'
        - '47-51'
      material: 'MAGENTA_STAINED_GLASS_PANE'
      display-name: "§c§l"

    back-ground-item-2:
      menu-slots:
        - '0-1'
        - '7-9'
        - '17-17'
        - '36-36'
        - '44-46'
        - '52-52'
      material: 'PURPLE_STAINED_GLASS_PANE'
      display-name: "§c§l"